- name: Configurar Ubuntu 24.04 - VM
  hosts: Ubuntu-Vagrant
  become: yes
  tasks:
    - name: Update & Upgrade
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

