FROM migvivcam/apache2:pr4

# Configura el entorno en modo no interactivo y define la zona horaria
COPY ./apache2.conf /etc/apache2/apache2.conf
COPY ./ssl.conf /etc/apache2/mods-available/ssl.conf
COPY ./post.php /var/www/html/post.php
# Actualiza, instala Apache y tzdata; configura la zona horaria de forma no interactiva
RUN a2enmod headers
RUN a2enmod rewrite
RUN a2dismod dav info
# Configura Apache para evitar advertencias por no tener definido ServerName
#RUN sudo echo "127.0.0.1 www.mvivas.com" >> /etc/hosts
# Expone el puerto 80
EXPOSE 80 443

# Inicia Apache en primer plano
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

