FROM migvivcam/apache2:pr3

# Configura el entorno en modo no interactivo y define la zona horaria

# Actualiza, instala Apache y tzdata; configura la zona horaria de forma no interactiva
RUN mkdir /etc/apache2/ssl
COPY apache.* /etc/apache2/ssl
COPY ./default-ssl /etc/apache2/sites-available/default-ssl.conf
RUN a2enmod ssl
RUN a2ensite default-ssl.conf
# Configura Apache para evitar advertencias por no tener definido ServerName
#RUN sudo echo "127.0.0.1 www.mvivas.com" >> /etc/hosts
# Expone el puerto 80
EXPOSE 80 443

# Inicia Apache en primer plano
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

