apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: myapp
data:
  traefik.yml: |
    log:
      level: DEBUG
    api:
      dashboard: true
      insecure: true
    entryPoints:
      web:
        address: ":4000"
      dashboard:
        address: ":8080"
    providers:
      kubernetesIngress: {}
      kubernetesCRD: {}