FROM migvivcam/apache2:pr2

# Actualiza e instala mod-evasive
RUN apt-get update && \
    apt-get install -y libapache2-mod-evasive

# Se copia la configuración de mod-evasive para que este en producción
COPY ./evasive /etc/apache2/mods-available/evasive.conf

# Expone el puerto 80
EXPOSE 80

# Inicia Apache en primer plano
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

