FROM migvivcam/apache2:pr2

# Configura el entorno en modo no interactivo y define la zona horaria

# Actualiza, instala Apache y tzdata; configura la zona horaria de forma no interactiva
RUN apt-get update && \
    apt-get install -y libapache2-mod-evasive
COPY ./evasive /etc/apache2/mods-available/evasive.conf
# Configura Apache para evitar advertencias por no tener definido ServerName

# Expone el puerto 80
EXPOSE 80

# Inicia Apache en primer plano
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

