FROM migvivcam/apache2:pr1

# Configura el entorno en modo no interactivo y define la zona horaria
ENV DEBIAN_FRONTEND=noninteractive

# Actualiza, instala Apache y tzdata; configura la zona horaria de forma no interactiva
RUN apt-get update && \
    apt-get install -y libapache2-mod-security2
RUN cp /etc/modsecurity/modsecurity.conf-recommended /etc/modsecurity/modsecurity.conf

## Configura Apache para evitar advertencias por no tener definido ServerName
COPY ./000-default /etc/apache2/sites-available/000-default.conf
COPY ./post.php /var/www/html/post.php
##

# Expone el puerto 80
EXPOSE 80

# Inicia Apache en primer plano
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
